# Pointing device / HID de mouse
CONFIG_ZMK_POINTING=y

# Subsistema de input + ADC + driver analogico do joystick
CONFIG_INPUT=y
CONFIG_ADC=y
CONFIG_ANALOG_INPUT=y

# Logging via USB (opcional): ajuda a ver leituras do ADC no monitor serial.
# Descomente pra debugar o centro/escala do joystick.
# CONFIG_ZMK_USB_LOGGING=y
